version: '2.3'

services:

  solrwin:
    image: solrwin:6.6.2
    build:
      context: .\solr
    hostname: solr
    ports:
      - "8983:8983"
    volumes:
      - ./data/solrhome:c:/data

networks:
  default:
    external:
      name: nat