version: '2.3'

services:

  solr-server:
    image: solr-win
    build:
      context: .\solr
    hostname: solr
    ports:
      - "8983:8983"
    environment:
      SOLR_HOME: g:/solrhome
    volumes:
      - ./data:c:/data

networks:
  default:
    external:
      name: nat